### ISSUE TITLE
atmega 328 internal 8mhz has a bad entry

### ISSUE THREAD

**Issue by dromie** [carlosefr/atmega#11]
atmega328.menu.clock.internal8.bootloader.high_fuses=0xdb

should be 

atmega328.menu.clock.internal8.bootloader.high_fuses=0xda

source:
https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoToBreadboard#minimal-circuit-eliminating-the-external-clock

**Comment by carlosefr** [comment]
The reason why the high fuse is set to `0xdb` is to disable the boot reset vector (`BOOTRST`) setting. `0xda` would be appropriate when using a bootloader (like on an Arduino), which is not the case here.

You can check this using the AVR Fuse Calculator: https://www.engbedded.com/fusecalc/
There's more information about `BOOTRST` here: https://www.martyncurrey.com/arduino-atmega-328p-fuse-settings/
