### ISSUE TITLE
Please create an updated release

### ISSUE THREAD

**Issue by DavidPowell** [carlosefr/atmega#3]
I would like to use the updated version of this board definition with the lower external clock speeds (FWIW to be compatible with 3.3V VCC), which I see already exists in master.

In the Arduino IDE 1.6.7 I have not been able to manually install the board definitions from the master .zip file.  No matter where I put the files the never seem to appear in the Tools->Board menu.

However the latest IDE still correctly interprets your json definition and updates the packages correcty, so it would be greatly appreciated if you could create a new release and update the json definition accordingly.

**Comment by carlosefr** [comment]
There is now a new release available.
