### ISSUE TITLE
Preserve EEPROM

### ISSUE THREAD

**Issue by aessig** [carlosefr/atmega#9]
Hello and thank you for this useful library.
Is there a way to prevent the EEPROM from being erased after each upload ?

**Comment by carlosefr** [comment]
You can edit the fuse configuration for the chip you're using in `boards.txt` (the Arduino IDE may, or may not, need a restart to detect the updated configuration).

For example, if you're using an ATmega 328p with an external 16 MHz clock, you can go to http://www.engbedded.com/fusecalc/ and input the fuse configuration from  `boards.txt` (`0xFF`, `0xDB`, `0xFD`) in the _current settings_ section. Then enable "Preserve EEPROM memory through the Chip Erase cycle; [EESAVE=0]" and you'll see the high fuse value change to `0xD3` while the other two stay the same. Update it in your `boards.txt` file and that should be it.
